version: '3.3'
services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"